# Generated by Django 3.0.4 on 2020-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='coordinates_lat',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='coordinates_lon',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateTimeField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='location',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweetText',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=1000),
        ),
    ]
