# Generated by Django 3.0.4 on 2020-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
