# Generated by Django 3.0.5 on 2020-04-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='username',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
    ]
