# Generated by Django 3.0.5 on 2020-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tweets_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='videoImage',
            field=models.CharField(default='NA', max_length=1000, null=True),
        ),
    ]
